# -*- coding: utf-8 -*-
"""stockpredict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pL9ECosH-i1eS1I1tCOYBHeWtCYa4Mfd
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pandas_datareader as data
from tensorflow.keras.models import load_model
import streamlit as st
import yfinance as yf


ticker = ''
start = '2010-01-01'
end = '2019-12-31'

st.title('Stock Trend Prediction')

user_input = st.text_input('Enter Stock Ticker', 'AAPL')
df = yf.download(user_input, start=start, end=end)



#Describing Data

st.subheader('Data from 2010-2019')
st.write(df.describe())